// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsjjhavnjrllvbvovyjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzampoYXZuanJsbHZidm92eWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Mzk0MzksImV4cCI6MjA3MjUxNTQzOX0.YcLQg_wHM6H-YxnyJi8R99LyEd1FDZCFD_espKVzEy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});